/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#6cf8bb",
        secondary: "#006c49",
        "surface-dim": "#cbdbf5",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#5516be",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-fixed": "#00fde8",
        "inverse-primary": "#00decc",
        "secondary-fixed-dim": "#4edea3",
        "on-primary-fixed-variant": "#005049",
        "on-surface-variant": "#3d4947",
        "tertiary-container": "#8455ef",
        "surface-container-low": "#eff4ff",
        "on-tertiary-container": "#fffbff",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary-fixed": "#002113",
        "on-tertiary": "#ffffff",
        "surface-container": "#e5eeff",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#00201d",
        error: "#ba1a1a",
        "surface-bright": "#f8f9ff",
        "on-tertiary-fixed": "#23005c",
        "on-secondary-fixed-variant": "#005236",
        "surface-variant": "#d3e4fe",
        "inverse-surface": "#213145",
        "on-surface": "#0b1c30",
        "on-primary-container": "#f4fffc",
        "tertiary-fixed-dim": "#d0bcff",
        "secondary-fixed": "#6ffbbe",
        background: "#f8f9ff",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-container": "#00714d",
        surface: "#f8f9ff",
        "primary-container": "#008378",
        outline: "#6d7a77",
        primary: "#00685f",
        "surface-tint": "#006a61",
        "on-background": "#0b1c30",
        "on-primary": "#ffffff",
        tertiary: "#6b38d4",
        "primary-fixed-dim": "#00decc",
        "tertiary-fixed": "#e9ddff",
        "outline-variant": "#bcc9c6",
        "surface-container-high": "#dce9ff"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        base: "4px",
        md: "24px",
        lg: "32px",
        "container-max": "1440px",
        gutter: "24px",
        "sidebar-width": "280px",
        sm: "16px",
        xs: "8px",
        xl: "48px"
      },
      fontFamily: {
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "display-lg": ["Inter"],
        "body-sm": ["Inter"],
        "title-md": ["Inter"],
        "headline-lg": ["Inter"],
        headline: ["Inter"],
        display: ["Inter"],
        body: ["Inter"],
        label: ["Inter"]
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
