import { useState, useEffect, useMemo } from 'react';
import { X, MapPin, CheckCircle2, ShieldCheck, AlertCircle, Loader2, Sparkles, User, Phone, Home, Layers } from 'lucide-react';
import { usePublicRegisterJemaah } from '../../hooks/useJemaah';
import { useSettings } from '../../contexts/SettingsContext';

// Generate a unique display ID outside of render
function generateDisplayId() {
  const timestamp = Date.now().toString(36).toUpperCase();
  const randomHex = Math.random().toString(36).substring(2, 6).toUpperCase();
  return `JMH-${timestamp}-${randomHex}`;
}

const JemaahRegistrationModal = ({ isOpen, onClose, onSuccess }) => {
  const { customData } = useSettings();
  const registerMutation = usePublicRegisterJemaah();

  // Auto-generate display ID on modal open
  const [displayId, setDisplayId] = useState(generateDisplayId);
  useEffect(() => {
    if (isOpen) {
      // eslint-disable-next-line react-hooks/set-state-in-effect -- Legitimate ID generation on modal open
      setDisplayId(generateDisplayId());
    }
  }, [isOpen]);
  const autoGeneratedId = displayId;

  const categories = useMemo(() => {
    const configured = customData?.jemaahStatus || [];
    const defaults = ['Umum', 'Muzakki', 'Mustahik', 'Fakir', 'Yatim', 'Lansia'];
    return Array.from(new Set([...defaults, ...configured]));
  }, [customData?.jemaahStatus]);

  const [formData, setFormData] = useState({
    name: '',
    category: 'Umum',
    phone: '',
    address: '',
    lat: null,
    lng: null
  });

  const [locationStatus, setLocationStatus] = useState('idle'); // 'idle' | 'loading' | 'success' | 'error'
  const [locationErrorMsg, setLocationErrorMsg] = useState('');
  const [validationError, setValidationError] = useState('');

  // Lock body scroll when modal is open & reset form
  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = 'hidden';
      // eslint-disable-next-line react-hooks/set-state-in-effect -- Legitimate form reset on modal open
      setFormData({
        name: '',
        category: 'Umum',
        phone: '',
        address: '',
        lat: null,
        lng: null
      });
      setLocationStatus('idle');
      setLocationErrorMsg('');
      setValidationError('');
    } else {
      document.body.style.overflow = '';
    }
    return () => {
      document.body.style.overflow = '';
    };
  }, [isOpen]);

  // Is Phone number mandatory for selected category?
  const isPhoneRequired = useMemo(() => {
    return ['Mustahik', 'Fakir', 'Yatim'].includes(formData.category);
  }, [formData.category]);

  const handleGetLocation = () => {
    if (!navigator.geolocation) {
      setLocationStatus('error');
      setLocationErrorMsg('Fitur Geolocation tidak didukung oleh perangkat/browser Anda.');
      return;
    }

    setLocationStatus('loading');
    setLocationErrorMsg('');

    navigator.geolocation.getCurrentPosition(
      (position) => {
        setFormData((prev) => ({
          ...prev,
          lat: position.coords.latitude,
          lng: position.coords.longitude
        }));
        setLocationStatus('success');
      },
      (error) => {
        console.warn('Geolocation permission error:', error);
        setLocationStatus('error');
        if (error.code === error.PERMISSION_DENIED) {
          setLocationErrorMsg('Akses lokasi ditolak oleh pengguna.');
        } else {
          setLocationErrorMsg('Gagal mendapatkan lokasi GPS. Pastikan GPS perangkat aktif.');
        }
      },
      { enableHighAccuracy: true, timeout: 10000, maximumAge: 0 }
    );
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    setValidationError('');

    // Strict validation checks
    if (!formData.name.trim()) {
      setValidationError('Nama Lengkap wajib diisi.');
      return;
    }

    if (!formData.address.trim()) {
      setValidationError('Alamat Lengkap wajib diisi.');
      return;
    }

    if (isPhoneRequired && (!formData.phone || !formData.phone.trim())) {
      setValidationError(`Nomor Telepon wajib diisi untuk Kategori ${formData.category}.`);
      return;
    }

    // Submit mutation
    registerMutation.mutate(
      {
        name: formData.name.trim(),
        category: formData.category,
        phone: formData.phone.trim() || '-',
        address: formData.address.trim(),
        lat: formData.lat,
        lng: formData.lng
      },
      {
        onSuccess: () => {
          if (onSuccess) {
            onSuccess(`Pendaftaran jemaah ${formData.name} berhasil disimpan!`);
          }
          onClose();
        },
        onError: (err) => {
          setValidationError(err.message || 'Gagal menyimpan data pendaftaran.');
        }
      }
    );
  };

  if (!isOpen) return null;

  return (
    <div
      onClick={onClose}
      className="fixed inset-0 z-[110] flex items-start sm:items-center justify-center bg-[#060b10]/90 p-4 sm:p-6 pt-12 sm:pt-8 overflow-y-auto animate-in fade-in duration-150"
    >
      <div
        onClick={(e) => e.stopPropagation()}
        className="bg-[#0b131a] border border-emerald-500/30 p-5 sm:p-8 rounded-3xl max-w-xl w-full relative space-y-5 sm:space-y-6 shadow-2xl my-auto text-white max-h-[90vh] overflow-y-auto"
      >
        {/* Modal Header */}
        <div className="flex justify-between items-start pt-1 pb-3 border-b border-white/10">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 flex items-center justify-center shrink-0">
              <Sparkles size={22} />
            </div>
            <div>
              <h2 className="text-xl font-bold text-white tracking-tight">Formulir Pendaftaran Jemaah Masjid</h2>
              <p className="text-xs text-slate-400">Silakan isi data jemaah di bawah ini secara lengkap</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-full bg-white/5 hover:bg-white/10 text-slate-400 hover:text-white transition-colors"
            aria-label="Tutup Form Pendaftaran"
          >
            <X size={20} />
          </button>
        </div>

        {/* Global Validation Error Message */}
        {validationError && (
          <div className="p-3.5 bg-rose-500/15 border border-rose-500/30 rounded-xl text-rose-300 text-xs flex items-center gap-2">
            <AlertCircle size={16} className="shrink-0 text-rose-400" />
            <span>{validationError}</span>
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-4">
          
          {/* Point 1: Auto-generated ID */}
          <div className="space-y-1.5">
            <label htmlFor="regId" className="text-xs font-semibold text-slate-300 flex items-center justify-between">
              <span>1. ID Pendaftaran Jemaah</span>
              <span className="text-[10px] text-emerald-400 font-mono">(Terisi otomatis oleh sistem)</span>
            </label>
            <input
              id="regId"
              type="text"
              readOnly
              value={autoGeneratedId}
              className="w-full px-4 py-2.5 bg-white/5 border border-white/10 rounded-xl font-mono text-xs text-emerald-400 outline-none cursor-not-allowed selection:bg-none"
            />
          </div>

          {/* Point 2: Nama Lengkap (Wajib) */}
          <div className="space-y-1.5">
            <label htmlFor="regName" className="text-xs font-semibold text-slate-300 flex items-center gap-1">
              <User size={14} className="text-amber-400" />
              <span>2. Nama Lengkap</span>
              <span className="text-rose-400 font-bold">* (Wajib diisi)</span>
            </label>
            <input
              id="regName"
              type="text"
              required
              placeholder="Contoh: Ahmad Subagja"
              value={formData.name}
              onChange={(e) => setFormData({ ...formData, name: e.target.value })}
              className="w-full px-4 py-2.5 bg-white/5 border border-white/15 focus:border-emerald-400 rounded-xl text-xs text-white placeholder:text-slate-500 outline-none transition-colors"
            />
          </div>

          {/* Point 3: Kategori Jemaah (Wajib) */}
          <div className="space-y-1.5">
            <label htmlFor="regCategory" className="text-xs font-semibold text-slate-300 flex items-center gap-1">
              <Layers size={14} className="text-amber-400" />
              <span>3. Kategori Jemaah</span>
              <span className="text-rose-400 font-bold">* (Wajib diisi)</span>
            </label>
            <select
              id="regCategory"
              value={formData.category}
              onChange={(e) => setFormData({ ...formData, category: e.target.value })}
              className="w-full px-4 py-2.5 bg-slate-900 border border-white/15 focus:border-emerald-400 rounded-xl text-xs text-white outline-none cursor-pointer appearance-none"
            >
              {categories.map((cat) => (
                <option key={cat} value={cat} className="bg-slate-900 text-white">
                  {cat} {['Mustahik', 'Fakir', 'Yatim'].includes(cat) ? '(Wajib sertakan No. Telepon)' : ''}
                </option>
              ))}
            </select>
          </div>

          {/* Point 4: Nomor Telepon (Wajib hanya untuk Mustahik, Fakir, Yatim) */}
          <div className="space-y-1.5">
            <label htmlFor="regPhone" className="text-xs font-semibold text-slate-300 flex items-center justify-between">
              <span className="flex items-center gap-1">
                <Phone size={14} className="text-amber-400" />
                <span>4. Nomor Telepon / WA</span>
              </span>
              {isPhoneRequired ? (
                <span className="text-rose-400 font-bold text-[11px]">* (Wajib diisi untuk Kategori {formData.category})</span>
              ) : (
                <span className="text-slate-400 text-[11px]">(Opsional untuk Kategori {formData.category})</span>
              )}
            </label>
            <input
              id="regPhone"
              type="tel"
              required={isPhoneRequired}
              placeholder="Contoh: 081234567890"
              value={formData.phone}
              onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
              className={`w-full px-4 py-2.5 bg-white/5 border rounded-xl text-xs text-white placeholder:text-slate-500 outline-none transition-colors ${
                isPhoneRequired && !formData.phone
                  ? 'border-amber-500/50 focus:border-amber-400'
                  : 'border-white/15 focus:border-emerald-400'
              }`}
            />
          </div>

          {/* Point 5: Alamat Lengkap (Wajib) */}
          <div className="space-y-1.5">
            <label htmlFor="regAddress" className="text-xs font-semibold text-slate-300 flex items-center gap-1">
              <Home size={14} className="text-amber-400" />
              <span>5. Alamat Lengkap</span>
              <span className="text-rose-400 font-bold">* (Wajib diisi)</span>
            </label>
            <textarea
              id="regAddress"
              required
              rows={2}
              placeholder="Contoh: Jl. Masjid No. 45 RT 02 / RW 04, Bandung"
              value={formData.address}
              onChange={(e) => setFormData({ ...formData, address: e.target.value })}
              className="w-full px-4 py-2.5 bg-white/5 border border-white/15 focus:border-emerald-400 rounded-xl text-xs text-white placeholder:text-slate-500 outline-none resize-none transition-colors"
            />
          </div>

          {/* Point 6: Permintaan Izin Akses Lokasi & Visualisasi Peta Interaktif */}
          <div className="p-4 bg-emerald-950/30 border border-emerald-500/25 rounded-2xl space-y-3">
            <div className="flex items-start gap-2.5">
              <div className="p-2 rounded-xl bg-emerald-500/20 text-emerald-400 shrink-0 mt-0.5">
                <MapPin size={18} />
              </div>
              <div className="space-y-1">
                <h4 className="text-xs font-bold text-white flex items-center gap-1.5">
                  <span>6. Akses Lokasi GPS (Peta Sebaran Jemaah)</span>
                  <span className="px-2 py-0.5 bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 rounded-full text-[10px]">Privasi Terjaga</span>
                </h4>
                {/* User's Exact Keterangan Requirement */}
                <p className="text-[11px] text-slate-300 leading-relaxed">
                  Permintaan izin akses lokasi hanya pada saat mendaftar pada pop up pendaftaran jemaah, dengan tambahan keterangan untuk menciptakan visualisasi peta interaktif sebaran jemaah pada landing page (Privasi Terjaga).
                </p>
              </div>
            </div>

            {/* GPS Location Trigger */}
            <div className="pt-1 flex flex-col sm:flex-row items-center justify-between gap-3">
              <button
                type="button"
                onClick={handleGetLocation}
                disabled={locationStatus === 'loading'}
                className="w-full sm:w-auto px-4 py-2 bg-emerald-500/20 hover:bg-emerald-500/30 text-emerald-300 border border-emerald-500/40 rounded-xl text-xs font-bold transition-all flex items-center justify-center gap-2 disabled:opacity-50"
              >
                {locationStatus === 'loading' ? (
                  <>
                    <Loader2 size={14} className="animate-spin text-emerald-400" />
                    <span>Mendapatkan Lokasi...</span>
                  </>
                ) : (
                  <>
                    <MapPin size={14} />
                    <span>{formData.lat ? 'Perbarui Lokasi GPS Saat Ini' : 'Izinkan & Dapatkan Lokasi GPS'}</span>
                  </>
                )}
              </button>

              {locationStatus === 'success' && formData.lat && (
                <div className="text-[11px] text-emerald-400 font-mono flex items-center gap-1 bg-emerald-500/10 px-2.5 py-1 rounded-lg border border-emerald-500/20">
                  <CheckCircle2 size={14} />
                  <span>GPS Terverifikasi ({formData.lat.toFixed(4)}, {formData.lng.toFixed(4)})</span>
                </div>
              )}
            </div>

            {locationErrorMsg && (
              <p className="text-[11px] text-amber-300 italic pt-1">{locationErrorMsg}</p>
            )}
          </div>

          {/* Form Actions */}
          <div className="pt-4 border-t border-white/10 flex gap-3">
            <button
              type="button"
              onClick={onClose}
              disabled={registerMutation.isPending}
              className="flex-1 py-3 px-4 rounded-xl border border-white/15 bg-white/5 hover:bg-white/10 text-slate-300 text-xs font-semibold transition-colors disabled:opacity-50"
            >
              Batal
            </button>
            <button
              type="submit"
              disabled={registerMutation.isPending}
              className="flex-1 py-3 px-4 rounded-xl bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-400 hover:to-teal-400 text-slate-950 font-extrabold text-xs transition-all shadow-lg shadow-emerald-500/20 flex items-center justify-center gap-2 disabled:opacity-50"
            >
              {registerMutation.isPending ? (
                <>
                  <Loader2 size={16} className="animate-spin text-slate-950" />
                  <span>Menyimpan...</span>
                </>
              ) : (
                <>
                  <CheckCircle2 size={16} />
                  <span>Kirim Pendaftaran Jemaah</span>
                </>
              )}
            </button>
          </div>

          <div className="flex items-center justify-center gap-1.5 text-[11px] text-slate-400 pt-1">
            <ShieldCheck size={14} className="text-emerald-400" />
            <span>Data Anda tersimpan secara aman dan terenkripsi dalam database masjid.</span>
          </div>

        </form>
      </div>
    </div>
  );
};

export default JemaahRegistrationModal;
